// Generated by scripts/gemini-e2e-cli.js.
// Model: gemini-3.1-flash-lite
// Generated at: 2026-07-01T12:17:35.337Z
// Review before committing if the generated assertions are important.
const { test, expect } = require('@playwright/test');

const VALID_COLOR = 'rgb(0, 128, 0)';
const INVALID_COLOR = 'rgb(255, 0, 0)';

const testCases = [
  { day: '1', month: '1', year: '2000', valid: true, desc: 'Valid date: 1/1/2000' },
  { day: '29', month: '2', year: '2000', valid: true, desc: 'Leap year: 29/2/2000' },
  { day: '29', month: '2', year: '1900', valid: false, desc: 'Non-leap year: 29/2/1900' },
  { day: '31', month: '4', year: '2000', valid: false, desc: 'Invalid day for month: 31/4/2000' },
  { day: '0', month: '1', year: '2000', valid: false, desc: 'Day out of range: 0' },
  { day: '1', month: '13', year: '2000', valid: false, desc: 'Month out of range: 13' },
  { day: '1', month: '1', year: '999', valid: false, desc: 'Year below range: 999' },
  { day: 'abc', month: '1', year: '2000', valid: false, desc: 'Non-numeric day' },
  { day: '1', month: '1', year: '3001', valid: false, desc: 'Year above range: 3001' },
  { day: '15', month: '6', year: '2023', valid: true, desc: 'Standard valid date' }
];

test.describe('DateTimeChecker UI Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  for (const tc of testCases) {
    test(tc.desc, async ({ page }) => {
      await page.fill('#day', tc.day);
      await page.fill('#month', tc.month);
      await page.fill('#year', tc.year);
      await page.click('button');

      const result = page.locator('#result');
      await expect(result).toBeVisible();
      await expect(result).toHaveCSS('color', tc.valid ? VALID_COLOR : INVALID_COLOR);
    });
  }
});
